# Trabajo en clase #3
## Sebastián Calvo
## Profesor: Osvaldo González
## Progra II - BD-143

### Paso 1: Carga de archivo 

In [ ]:
# Carga de librerías 
import pandas as pd
import numpy as np
import math as mt
import random as rd

In [2]:
# Carga de datos
datos = pd.read_csv('diabetes_V2.csv')
print(datos.head())

# Calcular la dimensión de la tabla de datos
tamanho = datos.shape
print("Tamaño del dataset:", tamanho)

# Calcule la suma de las columnas con variables cuantitativas (numéricas).
df_num = datos.select_dtypes(include=[np.number])

sumas = df_num.sum()

print("Suma de valores numéricos \n", sumas)

# Calcule la moda de las columnas con variables cualitativas (categóricas).
df_str = datos.select_dtypes(exclude=[np.number])
moda = df_str.mode()
print("La moda de las columna es: \n", moda)

   Unnamed: 0  colesterol  glucosa  hdl_chol  prop_col_hdl  edad  genero  \
0           1         193       77        49           3.9    19  female   
1           2         146       79        41           3.6    19  female   
2           3         217       75        54           4.0    20  female   
3           4         226       97        70           3.2    20  female   
4           5         164       91        67           2.4    20  female   

   altura  peso   IMC  ps_sistolica  ps_diastolica  cintura  caderas  \
0      61   119  22.5           118             70       32       38   
1      60   135  26.4           108             58       33       40   
2      67   187  29.3           110             72       40       45   
3      64   114  19.6           122             64       31       39   
4      70   141  20.2           122             86       32       39   

   prop_cin_cad     diabetes  
0          0.84  No_diabetes  
1          0.83  No_diabetes  
2          0.89  

## 2. Usando for(...) en Python muestre los números del 1 al 100 que terminan en 3.

In [3]:
num = 3
limite = 100

for indice in range(limite):
   if indice == num:
      print(num)
      num = num + 10
   if num >= 100:
      break  

3
13
23
33
43
53
63
73
83
93


## 3. Mediante un ciclo, calcule la sumatoria de los números enteros multiplos de 13, comprendidos entre el 1 y el 200.

In [4]:
limite = 200
sumatoria = 0

for indice in range(limite):
    if indice % 13 == 0:
        sumatoria = sumatoria + indice
        print(sumatoria)
    if indice >= 200:
        break    

0
13
39
78
130
195
273
364
468
585
715
858
1014
1183
1365
1560


## 4. Mediante un ciclo, guarde en una lista todos los números impares desde 1 hasta el 15.

In [5]:
num = 0

while num <= 15:
    impares = num % 2
    num = num + 1
    if impares == 0:
        print(num)    


1
3
5
7
9
11
13
15


## 5. Programe en Python una función que recibe tres valores A, B, y C y retorna menor.

In [6]:
def menor(A, B, C):
    if A > B < C:
        print("El menor es:", str(B))
    elif B > A < C:   
        print("El menor es:", str(A))
    else:
        print("El menor es:", C)

menor(4, 2, 7)

El menor es: 2


## 6. Programe en Python una función que genera 200 numeros al azar entre 1 y 500 y luego calcula cuantos están entre el 50 y 450, ambos inclusive.


In [ ]:
def numeros():
    lista = [rd.randint(1, 500) for _ in range(200)]
    contador = 0
    for i in lista:
        if i >= 50 and i <= 450:
            contador = contador + 1
    return(contador)        

print("La cantidad de números entre 50 y 450 es:",numeros())

La cantidad de números entre 50 y 450 es: 162


## 7.Desarrolle una funcion que reciba dos numeros enteros a y b, tal que, en un diccionario retorne el Máximo Común Divisor (MCD) y el mınimo comun multiplo (mcm). Para calcular el MCD puede utilizar la funcion gcd del paquete math.

In [ ]:

def calcular_mcd_mcm(a, b):
    mcd = math.gcd(a, b)
    mcm = abs(a * b) // mcd if mcd != 0 else 0
    
    return {
        "MCD": mcd,
        "mcm": mcm
    }

resultado = calcular_mcd_mcm(12, 18)
print(resultado)

{'MCD': 6, 'mcm': 36}


## Desarrolle una función que recibe una matriz cuadrada A de tamaño n × n y retorna su transpuesta (utilizando for).

In [8]:
matriz = np.array([[0, 20, 6],
                   [4, 12, 48],
                   [-8, -5, -16]])

def matriz_TRANS():
    linea1 = []
    linea2 = []
    linea3 = []

    for x in np.nditer(matriz[:, 0]):
        linea1.append(x)

    for x in np.nditer(matriz[:, 1]):
        linea2.append(x)

    for x in np.nditer(matriz[:, 2]):
        linea3.append(x)

    nueva_matriz = np.array([linea1, linea2, linea3])  
    return nueva_matriz

print(matriz_TRANS())

[[  0   4  -8]
 [ 20  12  -5]
 [  6  48 -16]]


## 9. Desarrolle una funcion que recibe un DataFrame y un nombre de columna y que retorne un diccionario con los valores de la  media, mínimo, máximo y mediana de dicha columna del dataframe. Verifique la correctitud de esta funcion usando la tabla Players1.csv y la columna minutes, que hace referencia a los minutos de juego.

In [5]:
players = pd.read_csv('Players1.csv')
print(players)

def diccionario(df, ic):
    columna_seleccionada = df.iloc[:, ic].values

    resultado = {
        "media": float(np.mean(columna_seleccionada)),
        "mediana": float(np.median(columna_seleccionada)),
        "minimo": float(np.min(columna_seleccionada)),
        "maximo": float(np.max(columna_seleccionada))
    }
    
    return resultado

estadisticas = diccionario(players, 3)
print(estadisticas)

           surname     team    position  minutes  shots  passes  tackles  \
0           Abdoun  Algeria  midfielder       16      0       6        0   
1          Belhadj  Algeria    defender      270      1     146        8   
2        Boudebouz  Algeria  midfielder       74      3      28        1   
3        Bougherra  Algeria    defender      270      1      89       11   
4         Chaouchi  Algeria  goalkeeper       90      0      17        0   
..             ...      ...         ...      ...    ...     ...      ...   
590         Holden      USA  midfielder        4      0       2        0   
591         Howard      USA  goalkeeper      390      0      81        0   
592  Jozy Altidore      USA     forward      356      8      84        2   
593         Onyewu      USA    defender      170      1      69        2   
594     Torres 2 3      USA  midfielder       45      1      32        0   

     saves  
0        0  
1        0  
2        0  
3        0  
4        2  
..     ..

## 10. Desarrolle una función que recibe un DataFrame y dos numeros de columna y que retorna la correlacion entre esas dos variables. Verifique la correctitud de esta funcion usando la tabla Players1.csv y las columnas 5 y 6, que hacen referencia a las variables shots y passes.

In [7]:
def calcular_correlacion(df, ic1, ic2):
    columna1 = df.iloc[:, ic1]
    columna2 = df.iloc[:, ic2]

    correlacion = columna1.corr(columna2)
    return correlacion

resultado = calcular_correlacion(players, 4, 5)

print(resultado)

0.34316326457351604
